name = "image-bg-remover-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "user_db"
database_name = "user-db"
database_id = "8d7ac785-f126-4866-ac13-3cecc2081774"

# PayPal 配置
[vars]
PAYPAL_MODE = "sandbox"

# Secrets - 通过 wrangler secret put 设置
# PAYPAL_CLIENT_ID
# PAYPAL_CLIENT_SECRET